apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prisma-web-ingress
  namespace: prisma-web
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: license.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: license-server
                port:
                  number: 3000
